
webservice:
    host: localhost
    port: 1337

log:
  verbose: true
  filepath: config/sortdc.log

classifiers:

  thematics:
    database:
      dbms: mysql
      #host: localhost
      #port: 27017
      dbname: sortdc_thematics
      username: sortdc_thematics
      password: azerty
    lang: french
    stemming: true
    autotrain: true
    autotrain_threshold: 0.7
    words_min_length: 3
    stopwords_file: config/stopwords.txt
    
  languages:
    database:
      dbms: mysql
      host: localhost
      #port: 3306
      dbname: sortdc_languages
      username: sortdc_languages
      password: azerty
    words: false
    ngrams_chars: [2, 3]
    #ngrams_words: 2
    stopwords: [la, le, les, ce, ces, ça]
