
log:
  verbose: true
  filepath: config/sortdc.log

database:
  dbms: mongodb
  host: localhost
  port: 27017
  dbname: sortdc
  #username: azerty
  #password: azerty

classifiers:

  - name: thematics
    lang: french
    stemming: true
    autotrain: true
    autotrain_threshold: 0.7
    multicategories: true
    stopwords_file: config/stopwords.txt
    
  - name: languages
    words: false
    ngrams_chars: [2, 3]
    #ngrams_words: 2
    stopwords: [la, le, les, ce, ces, ça]
